### ISSUE TITLE
packaging for brew manager?

### ISSUE THREAD

**Issue by judzen** [nh2tran/DeepNovo#1]
Awesome tool-- just wanted to see if the authors had any intention on making DeepNovo available via the brew package manager...  it simplifies things for a specific type of user...  

At any rate, I can't wait to pull the source...  

Thanks,
J

**Comment by nh2tran** [comment]
Hi @judzen , thanks for your interest. As the tool still needs a lot of development & cleaning, and we have limited resources on this project, we may not be able to do it for now.
