### ISSUE TITLE
Cython compatible version 

### ISSUE THREAD

**Issue by cguetot** [nh2tran/DeepNovo#3]
Hi,

1. Since you're making changes in tensorflow, Can you please specify which version of Cython should I use according to the two reported tensorflow version used in DeepNovo?

2. Do you have a container of DeepNovo?  I am trying to run it and keep getting errors (I already mailed to nh2tran@uwaterloo.ca with details)

thanks in advance

**Comment by nh2tran** [comment]
Thank you for your interest.

I have updated the data and model folders. Details are in the reply email to yours.

I used Cython 0.22. But it doesn't have to be compatible with Tensorflow version. We just use it to speed up some Numpy operations.
