### ISSUE TITLE
AssertionError: Error: wrong input PEPMASS

### ISSUE THREAD

**Issue by cguetot** [nh2tran/DeepNovo#4]
Hi Heiu,

I have mzml files which were converted to mgf extension using ProteoWizard. I get this error from deepnovo

'''
Traceback (most recent call last):
  File "/opt/DeepNovo/deepnovo_main.py", line 83, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/opt/DeepNovo/deepnovo_main.py", line 61, in main
    predicted_denovo_list = worker_denovo.search_denovo(model, worker_io)
  File "/opt/DeepNovo/deepnovo_worker_denovo.py", line 109, in search_denovo
    spectrum_batch = worker_io.get_spectrum(location_batch)
  File "/opt/DeepNovo/deepnovo_worker_io.py", line 93, in get_spectrum
    intensity_list) = self._parse_spectrum(location)
  File "/opt/DeepNovo/deepnovo_worker_io.py", line 208, in _parse_spectrum
    precursor_mz, charge, scan, raw_sequence = self._parse_spectrum_header()
  File "/opt/DeepNovo/deepnovo_worker_io.py", line 225, in _parse_spectrum_header
    assert "PEPMASS=" in line, "Error: wrong input PEPMASS"

'''
It looks like is an incompatibility issue related to the format of you're using and the one obtained from ProteoWizard.  Check the first lines of both files:

Your example file ( peaks.db.mgf.test.dup)
------------------------------------------------
''
'BEGIN IONS
TITLE=C:\Users\nh2tran\WORKING\DeepNovo\DeepDB\PEAKS\yeast.low.coon_2013\run_ALL_C:\Users\nh2tran\WORKING\DeepNovo\DeepDB\data\yeast.low.coon_2013\singleShot_Fusion-1493228696289\10sep2013_yeast_control_1.raw_SCANS_1393
PEPMASS=304.494
CHARGE=3+
SCANS=F1:1393
RTINSECONDS=131.85599
SEQ=QIVHDSGR
120.147 14.099166
120.784 43.689667
127.063 20.362473

'''

Obtained from Proteowizard
-------------------------------

'''
BEGIN IONS
TITLE=KristofferS_H1507_145.2.2.1 File:"KristofferS_H1507_145.raw", NativeID:"controllerType=0 controllerNumber=1 scan=2"
RTINSECONDS=0.6773028
PEPMASS=391.285153404545 1214043.75
CHARGE=1+
149.0232544 524525.5138634257
150.0265961 19292.7731562133
167.0337524 28203.4820123287
172.3424682 858.6995042906
183.1525574 775.4042822765
'''

I already tried these without any success:
1. Delete the second column in PEPMASS
2. Reduce the number of decimal for the value in PEPMASS

Questions:
a. Do you think is this associated with the order of the LABELS?
b. Do you recommend a particular converter?

best

Carlos

**Comment by nh2tran** [comment]
Hi Carlos,

The functions  _parse_spectrum_header() expects the input file to have all
the header lines in the following order:
TITLE=<value>
PEPMASS=<value>
CHARGE=<value>
SCANS=<value>
RTINSECONDS=<value>
SEQ=<value>

If you input file, for example from ProteoWizard, doesn't have those lines,
you  can append them with value equal empty sequence. Alternatively, you
can modify the code in  deepnovo_worker_io to read your format.

Regards,
hieu
