### ISSUE TITLE
ImportError: No module named Bio

### ISSUE THREAD

**Issue by sorenwacker** [nh2tran/DeepNovo#5]
Are there more dependencies? I am getting the following error, when I try the code in the readme file.

```
> python deepnovo_main.py --train_dir train.example --decode --beam_search --beam_size 5
from Bio import SeqIO
ImportError: No module named Bio
```

**Comment by nh2tran** [comment]
Hi, thank you for your interest. Please install biopython (https://biopython.org/wiki/Download).
