### ISSUE TITLE
Missing files in data.training?

### ISSUE THREAD

**Issue by yfukasawa** [nh2tran/DeepNovo#9]
Hi @nh2tran ,

Thank you for your development!

I'm trying to run your DeepNovo on my machine, and tentatively cloned and downloaded required files (and downgladed TF to 1.2).

After Cython compilation, I run the below command and faced an error:
`python deepnovo_main.py --train_dir train.example --decode --beam_search --beam_size 5`

**[Errno 2] No such file or directory: 'data.training/dia.xchen.nov27/fraction_1.mgf.split.test.dup'**

In your google drive, dia.xchen.nov27/fraction_1.mgf.split.test.dup does not exist.
This looks line a DIA data, and if so, which lines I should comment out in the config file to test?

Please advise.

Best,
Yoshinori

**Comment by nh2tran** [comment]
Hi Yoshinori,

The test file provided in my google drive corresponds to this line:
decode_test_file = "data.training/yeast.low.coon_2013/peaks.db.mgf.test.dup"

**Comment by xingchangrui** [comment]
> Hi nh2tran
Thank you for your development!  I'm  trying to learn  the DeepNovo. 

An error was showed when commond“ python deepnovo_main.py --train_dir train.example --train”was run.

IOError: [Errno 2] No such file or directory: 'data.training/yeast.low.coon_2013/peaks.db.mgf.train.dup' 

There are only one file "peaks.db.mgf.test.dup" in your google drive. 
The following two files could not be found. Could you tell me where to find it?  

    input_file_train = "data.training/yeast.low.coon_2013/peaks.db.mgf.train.dup"
    input_file_valid = "data.training/yeast.low.coon_2013/peaks.db.mgf.valid.dup"

Thank you very much!

Best,
Rui
